# Generated by Django 6.0.2 on 2026-03-08 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='messege',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='grade',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='e_diary.diary'),
        ),
    ]
