# Generated by Django 6.0.2 on 2026-03-25 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_diary', '0002_grade_messege_alter_grade_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='user_profile',
            new_name='diary_connection',
        ),
    ]
