# Generated by Django 5.2.8 on 2026-03-20 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_alter_profile_avatar_alter_profile_user_and_more"),
        ("portfolio", "0003_alter_sociallink_platform"),
    ]

    operations = []
