# Generated by Django 5.2.8 on 2026-03-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_merge_20260320_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.CharField(blank=True, choices=[('beginner', 'Початковий'), ('intermediate', 'Середній'), ('advanced', 'Продвинутий')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
    ]
