# Generated by Django 5.2.8 on 2026-03-21 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_system', '0002_voting_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='is_active',
        ),
        migrations.AddField(
            model_name='voting',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 28, 15, 53, 59, 952532, tzinfo=datetime.timezone.utc), verbose_name='Дата завершення'),
        ),
    ]
